[build]
  command = "CI=false npm install --legacy-peer-deps --force && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NETLIFY_USE_YARN = "false"

[context.production.environment]
  REACT_APP_API_BASE_URL = "https://backend-a2q3.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"
